version: '3.7'

services:

  playkot-services-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: playkot-services-frontend
    ports:
      - "4200:80"

  nginx:
    image: nginx:1.23-alpine
    container_name: playkot-services-frontend-nginx
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"