version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - .:/opt/app
    command: [ 'python', '/opt/app/cli.py', 'likes' ]
    working_dir: '/opt/app'
    restart: on-failure