version: '3.3'

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asana-api
    ports:
      - '80:80'
    volumes:
      - .:/opt/app
    command: [ 'python', '/opt/app/cli.py', 'api' ]
    working_dir: '/opt/app'
